const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '..', 'public/locales/en/translation.json');
const tiPath = path.join(__dirname, '..', 'public/locales/ti/translation.json');
const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const ti = JSON.parse(fs.readFileSync(tiPath, 'utf8'));

// Tigrinya translations for all remaining keys (admin, account, dashboard, orders, etc.)
const tiTranslations = {
  // --- Admin / Dashboard ---
  "A unified trail of important actions across Orders and Inventory.": "ሓድ ዝተወሃሃደ ዱካ ኣገደስቲ ተግባራት ኣብ ትእዛዛትን ዕቃን።",
  "API Keys": "መፍትሕ API",
  "API calls taking >1000ms should be optimized": "ካብ 1000ms ንላዕሊ ዝወስዱ API ጻውዒታት ክመሓየሹ ኣለዎም",
  "API documentation": "ሰነድ API",
  "Access all features": "ኩሎም ባህርያት ተጠቐም",
  "Access removed.": "ኣክሰስ ተኣልዩ።",
  "Account & Security": "ኣካውንትን ድሕነትን",
  "Account Access": "ኣክሰስ ኣካውንት",
  "Account Information": "ሓበሬታ ኣካውንት",
  "Account Lockouts Active": "ንጡፋት ምዕጻው ኣካውንት",
  "Account Status": "ኩነታት ኣካውንት",
  "Account recovery options": "ኣማራጺታት ምምላስ ኣካውንት",
  "Account security events": "ፍጻመታት ድሕነት ኣካውንት",
  "Account verified": "ኣካውንት ተረጋጊጹ",
  "Action": "ተግባር",
  "Actions": "ተግባራት",
  "Actions:": "ተግባራት:",
  "Activate": "ኣንቅሕ",
  "Active": "ንጡፍ",
  "Active Alerts": "ንጡፋት ማንቂታት",
  "Active Customers": "ንጡፋት ዓማዊል",
  "Actor email": "ኢመይል ተዋሳኣይ",
  "Add": "ወስኽ",
  "Add Card": "ካርድ ወስኽ",
  "Add New Webhook": "ሓድሽ Webhook ወስኽ",
  "Add Webhook": "Webhook ወስኽ",
  "Add a note...": "ማስታወሻ ወስኽ...",
  "Add new": "ሓድሽ ወስኽ",
  "Address Line 1": "ኣድራሻ መስመር 1",
  "Admin": "ኣድሚን",
  "Admin Only:": "ኣድሚን ጥራይ:",
  "Admin Order": "ናይ ኣድሚን ትእዛዝ",
  "Admin Orders": "ናይ ኣድሚን ትእዛዛት",
  "Admin Role": "ተራ ኣድሚን",
  "Admin note": "ናይ ኣድሚን ማስታወሻ",
  "Admin note (optional)": "ናይ ኣድሚን ማስታወሻ (ኣማራጺ)",
  "After": "ድሕሪ",
  "All": "ኩሉ",
  "All login attempts appear normal": "ኩሎም ፈተነታት ምእታው ንቡር ይመስሉ",
  "All statuses": "ኩሎም ኩነታት",
  "Amount": "መጠን",
  "Android device": "መሳርሒ ኣንድሮይድ",
  "Approve": "ኣጽድቕ",
  "Assertion Consumer Service (ACS) URL:": "URL ናይ ACS:",
  "Assign backoffice roles to staff users.": "ንስራሕተኛታት ተራ ባክኦፊስ ምድብ።",
  "At least 8 characters recommended": "ብውሕዱ 8 ፊደላት ይምከር",
  "Audit Logs": "ናይ ኦዲት ሎጋት",
  "Audit logs are retained for 90 days. Logs beyond this period are archived and can be exported from your security dashboard.": "ናይ ኦዲት ሎጋት ን90 መዓልታት ይዕቀቡ። ካብዚ ግዜ ንላዕሊ ዝኾኑ ሎጋት ኣርካይቭ ኮይኖም ካብ ዳሽቦርድ ድሕነት ክወጹ ይኽእሉ።",
  "Author (EN)": "ጸሓፊ (EN)",
  "Author (TI)": "ጸሓፊ (TI)",
  "Auto-refresh": "ባዕሉ-ሓድሽ",
  "Auto-refresh: Off": "ባዕሉ-ሓድሽ: ዕጹው",
  "Auto-refresh: On": "ባዕሉ-ሓድሽ: ክፉት",
  "Automated backup and disaster recovery": "ኣውቶማቲክ ባክኣፕን ናይ ሓደጋ ምምላስን",
  "Average API Response Time": "ማእከላይ ግዜ መልሲ API",
  "Avg Order Value": "ማእከላይ ዋጋ ትእዛዝ",
  "Avg first response (mins)": "ማእከላይ ቀዳማይ መልሲ (ደቓይቕ)",
  "Back cover": "ድሕሪት ገጽ",
  "Backoffice Groups": "ጉጅለታት ባክኦፊስ",
  "Backordered": "ተመሊሱ ዝተኣዘዘ",
  "Basic details about your workspace": "መሰረታዊ ዝርዝር ብዛዕባ ስራሕ ቦታኻ",
  "Before": "ቅድሚ",
  "Billed Monthly • $29.99/month": "ወርሓዊ ክፍሊት • $29.99/ወርሒ",
  "Billing & Subscription": "ክፍሊትን ምዝገባን",
  "Billing Issue": "ጸገም ክፍሊት",
  "Blacklisted IPs": "ዝተኣገዱ IP-ታት",
  "Block IP": "IP ዕገት",
  "Book details": "ዝርዝር መጽሓፍ",
  "Breaches and response time from recent tickets": "ግህሰታትን ግዜ መልስን ካብ ቀረባ ቲከታት",
  "Breakdown of assessed login risk levels": "ትንተና ናይ ዝተገምገሙ ደረጃታት ሓደጋ ምእታው",
  "Browser session": "ክፍለ-ግዜ ብራውዘር",
  "Bulk action": "ብጅምላ ተግባር",
  "Bulk action completed for {{count}} orders.": "ብጅምላ ተግባር ን{{count}} ትእዛዛት ተዛዚሙ።",
  "Bulk action completed with {{success}} successes and {{failed}} failures.": "ብጅምላ ተግባር ብ{{success}} ዓወትን {{failed}} ውድቀትን ተዛዚሙ።",
  "Bulk action failed for all selected orders.": "ብጅምላ ተግባር ንኹሎም ዝተመርጹ ትእዛዛት ፈሺሉ።",
  "Bulk action failed.": "ብጅምላ ተግባር ፈሺሉ።",
  "Bulk status": "ብጅምላ ኩነታት",
  "Cancel Order": "ትእዛዝ ሰርዝ",
  "Cancel Refund Request": "ሕቶ ምምላስ ገንዘብ ሰርዝ",
  "Cancel Return Request": "ሕቶ ምምላስ ሰርዝ",
  "Cancel orders": "ትእዛዛት ሰርዝ",
  "Cannot manage team": "ጋንታ ምምሕዳር ኣይከኣልን",
  "Carrier": "ተሸካሚ",
  "Carrier URL": "URL ተሸካሚ",
  "Carrier and tracking number are required to mark an order as SHIPPED.": "ትእዛዝ ከም ዝተላእከ ንምምልካት ተሸካምን ቁጽሪ ትራኪንግን ይድለ።",
  "Carrier and tracking number are required to mark orders as SHIPPED.": "ትእዛዛት ከም ዝተላእኹ ንምምልካት ተሸካምን ቁጽሪ ትራኪንግን ይድለ።",
  "Catalog products": "ፍርያት ካታሎግ",
  "Certificate (PEM format)": "ሰርቲፊኬት (ቅርጺ PEM)",
  "Certification (EN)": "ምስክር (EN)",
  "Certification (TI)": "ምስክር (TI)",
  "Change Plan": "ፕላን ቀይር",
  "Change workspace settings": "ሰቲንግ ስራሕ ቦታ ቀይር",
  "Change your password regularly to keep your account secure": "ኣካውንትኻ ውሑስ ንኽኸውን ቃል-ምስጢርካ ብቐጻሊ ቀይር",
  "Changed mind": "ሓሳብ ቀይረ",
  "Changing payment method": "ኣገባብ ክፍሊት ይቕየር ኣሎ",
  "Choose a product type to continue.": "ንምቕጻል ዓይነት ፍርያት ምረጹ።",
  "Choose how you want to be notified about your account activity": "ብዛዕባ ንጥፈታት ኣካውንትኻ ብኸመይ ክትሕበር ከም ትደሊ ምረጽ",
  "Clear logs": "ሎጋት ኣጽሪ",
  "Click to upload": "ንምጽዓን ጠውቕ",
  "Close": "ዕጾ",
  "Coming soon": "ቀርቢ ይመጽእ",
  "Compliance & Certifications": "ተሰማምዕነትን ምስክራትን",
  "Configure enterprise single sign-on for your team": "ንጋንታኻ ናይ ኢንተርፕራይዝ SSO ኣተዓራሪ",
  "Configure webhooks to receive real-time notifications": "ናይ ብቐጥታ ሓበሬታ ንምቕባል webhooks ኣተዓራሪ",
  "Configuring inventory": "ዕቃ ይተዓራረ ኣሎ",
  "Confirmation sent to": "ምርግጋጽ ናብ ተሰዲዱ",
  "Consider adding caching for frequently accessed endpoints": "ብተደጋጋሚ ዝርከቡ endpoints ንምህርፋን cache ምውሳኽ ተሓሰብ",
  "Control Center": "ማእከል ምቁጽጻር",
  "Conversion Rate": "ምጣነ ለውጢ",
  "Copied invite link.": "ናይ ዕድመ ሊንክ ተቐዲሑ።",
  "Copy": "ቅዳሕ",
  "Copy key": "መፍትሕ ቅዳሕ",
  "Cover": "ገጽ",
  "Create Key": "መፍትሕ ፍጠር",
  "Create New API Key": "ሓድሽ መፍትሕ API ፍጠር",
  "Create Webhook": "Webhook ፍጠር",
  "Create invite": "ዕድመ ፍጠር",
  "Created": "ተፈጢሩ",
  "Created On": "ዝተፈጥረሉ ዕለት",
  "Created:": "ተፈጢሩ:",
  "Critical": "ህጹጽ",
  "Current": "ሕጂ ዘሎ",
  "Current Plan": "ሕጂ ዘሎ ፕላን",
  "Current Plan: Pro": "ሕጂ ዘሎ ፕላን: Pro",
  "Currently locked": "ሕጂ ተዓጽዩ",
  "Custom development": "ዕዮ ብደላይ",
  "Customer": "ዓሚል",
  "Customer Report": "ሪፖርት ዓሚል",
  "Customer status updated.": "ኩነታት ዓሚል ተመሓዪሹ።",
  "Customer:": "ዓሚል:",
  "Customers": "ዓማዊል",
  "Cycle": "ዙርያ",
  "Damaged item": "ዝተበላሸወ ኣቑሑ",
  "Danger Zone": "ሓደገኛ ከባቢ",
  "Dashboard Overview": "ጽሟቕ ዳሽቦርድ",
  "Data Protection Measures": "ስጉምትታት ምሕላው ዳታ",
  "Data retention and deletion policies in place": "ፖሊሲታት ምዕቃብን ምድምሳስን ዳታ ኣብ ቦታ",
  "Date": "ዕለት",
  "Date range": "ክፍተት ዕለት",
  "Days Left": "ዝተረፈ መዓልታት",
  "Deactivate": "ኣጥፍእ",
  "Default": "ንቡር",
  "Delete Workspace": "ስራሕ ቦታ ደምስስ",
  "Delete failed.": "ምድምሳስ ፈሺሉ።",
  "Delete product": "ፍርያት ደምስስ",
  "Delete this image?": "እዚ ስእሊ ክድምሰስ?",
  "Delivered": "ተበጺሑ",
  "Delivered On": "ዝተበጽሐሉ ዕለት",
  "Deliveries": "ምብጻሓት",
  "Delivery Timeline": "ግዜ ሰሌዳ ምብጻሕ",
  "Describe the issue...": "ጸገሙ ግለጹ...",
  "Details (optional)": "ዝርዝር (ኣማራጺ)",
  "Device Management": "ምምሕዳር መሳርሒ",
  "Discount": "ቅናስ",
  "Discover Selsa Store": "ድኳን ሰልሳ ድለዩ",
  "Download": "ኣውርድ",
  "Download Certifications": "ምስክራት ኣውርድ",
  "Download your billing invoices": "ናይ ክፍሊት ኢንቮይስ ኣውርድ",
  "Edit": "ኣርም",
  "Edit Profile": "ፕሮፋይል ኣርም",
  "Edit note": "ማስታወሻ ኣርም",
  "Edit note...": "ማስታወሻ ኣርም...",
  "Email Notifications": "ናይ ኢመይል ሓበሬታታት",
  "Email is required.": "ኢመይል ይድለ።",
  "End-to-end encryption for all data transfers": "ንኹሉ ምስግጋር ዳታ ካብ ጫፍ ናብ ጫፍ ምስጢራውነት",
  "Enjoy your new items from Selsa.": "ሓደስቲ ኣቑሑትኩም ካብ ሰልሳ ተሓጎሱ።",
  "Error accepting invite": "ዕድመ ኣብ ምቕባል ጌጋ",
  "Errors": "ጌጋታት",
  "Estimated Delivery": "ግምት ምብጻሕ",
  "Event Type": "ዓይነት ፍጻመ",
  "Event type": "ዓይነት ፍጻመ",
  "Every": "ነፍሲ ወከፍ",
  "Expires": "ዝወድቀሉ",
  "Explore Collections": "ትሕስቶታት ርአ",
  "Explore Enterprise Plan": "ናይ ኢንተርፕራይዝ ፕላን ርአ",
  "Export": "ኣውጽእ",
  "Export CSV": "CSV ኣውጽእ",
  "Export failed.": "ምውጻእ ፈሺሉ።",
  "Exporting...": "ይወጽእ ኣሎ...",
  "Failed Attempts": "ዝፈሸሉ ፈተነታት",
  "Failed Attempts:": "ዝፈሸሉ ፈተነታት:",
  "Failed Count": "ብዝሒ ውድቀት",
  "Failed to add note.": "ማስታወሻ ምውሳኽ ፈሺሉ።",
  "Failed to approve request.": "ሕቶ ምጽዳቕ ፈሺሉ።",
  "Failed to delete image.": "ስእሊ ምድምሳስ ፈሺሉ።",
  "Failed to delete note.": "ማስታወሻ ምድምሳስ ፈሺሉ።",
  "Failed to invite staff.": "ስራሕተኛ ምዕዳም ፈሺሉ።",
  "Failed to load audit logs.": "ናይ ኦዲት ሎጋት ምጽዓን ፈሺሉ።",
  "Failed to load customer.": "ዓሚል ምጽዓን ፈሺሉ።",
  "Failed to load customers.": "ዓማዊል ምጽዓን ፈሺሉ።",
  "Failed to load inventory audit events.": "ናይ ዕቃ ኦዲት ፍጻመታት ምጽዓን ፈሺሉ።",
  "Failed to load order audit logs.": "ናይ ትእዛዝ ኦዲት ሎጋት ምጽዓን ፈሺሉ።",
  "Failed to load product.": "ፍርያት ምጽዓን ፈሺሉ።",
  "Failed to load products.": "ፍርያታት ምጽዓን ፈሺሉ።",
  "Failed to load reports.": "ሪፖርታት ምጽዓን ፈሺሉ።",
  "Failed to load staff.": "ስራሕተኛታት ምጽዓን ፈሺሉ።",
  "Failed to load timeline.": "ግዜ ሰሌዳ ምጽዓን ፈሺሉ።",
  "Failed to mark order as shipped.": "ትእዛዝ ከም ዝተላእከ ምምልካት ፈሺሉ።",
  "Failed to mark return received.": "ምምላስ ከም ዝተቐበልና ምምልካት ፈሺሉ።",
  "Failed to refresh.": "ሓድሽ ምግባር ፈሺሉ።",
  "Failed to reject request.": "ሕቶ ምንጻግ ፈሺሉ።",
  "Failed to remove access.": "ኣክሰስ ምእላይ ፈሺሉ።",
  "Failed to reorder images.": "ስእሊታት ብሓድሽ ምስርዓው ፈሺሉ።",
  "Failed to resend shipping email.": "ናይ ምልኣኽ ኢመይል ደጊምካ ምስዳድ ፈሺሉ።",
  "Failed to revoke other sessions": "ካልኦት ክፍለ-ግዜታት ምስራዝ ፈሺሉ",
  "Failed to revoke session": "ክፍለ-ግዜ ምስራዝ ፈሺሉ",
  "Failed to save notification preferences": "ምርጫታት ሓበሬታ ምዕቃብ ፈሺሉ",
  "Failed to set primary image.": "ቀንዲ ስእሊ ምምልካት ፈሺሉ።",
  "Failed to update note.": "ማስታወሻ ምምሕያሽ ፈሺሉ።",
  "Failed to update promotional email preference": "ናይ ፕሮሞሽን ኢመይል ምርጫ ምምሕያሽ ፈሺሉ",
  "Failed to update staff access.": "ናይ ስራሕተኛ ኣክሰስ ምምሕያሽ ፈሺሉ።",
  "Failed to update status.": "ኩነታት ምምሕያሽ ፈሺሉ።",
  "Failed/Success": "ፈሺሉ/ተሰሊጡ",
  "Failure rate:": "ምጣነ ውድቀት:",
  "Failures": "ውድቀታት",
  "Feb 24, 2026": "ለካቲት 24, 2026",
  "Filter status": "ኩነታት ፊልተር",
  "Filters": "ፊልተራት",
  "Find answers to common questions and learn how to use Selsa": "ንልሙዳት ሕቶታት መልሲ ርኸቡን ሰልሳ ብኸመይ ከም ትጥቀሙ ተማሃሩን",
  "First response breached": "ቀዳማይ መልሲ ተጊሒሱ",
  "Food product created": "ናይ መግቢ ፍርያት ተፈጢሩ",
  "Fulfillment Pending": "ምምላእ ይጽበ ኣሎ",
  "Fulfillment Pipeline": "ጽርግያ ምምላእ",
  "Fulfillment Queue": "ተርታ ምምላእ",
  "Full account access": "ምሉእ ኣክሰስ ኣካውንት",
  "General Question": "ሓፈሻዊ ሕቶ",
  "Get help from our support team. We typically respond within 24 hours": "ካብ ጋንታ ደገፍና ሓገዝ ርኸቡ። ብልሙድ ኣብ ውሽጢ 24 ሰዓታት ንምልስ",
  "Getting Started": "ምጅማር",
  "Go to Risk Monitoring": "ናብ ምክትታል ሓደጋ",
  "Go to Support": "ናብ ደገፍ",
  "Guest": "ጋሻ",
  "Help Center": "ማእከል ሓገዝ",
  "High": "ልዑል",
  "High - Urgent": "ልዑል - ህጹጽ",
  "High Failure Rate": "ልዑል ምጣነ ውድቀት",
  "How do I cancel my subscription?": "ምዝገባይ ብኸመይ ክስርዝ?",
  "How to create your first store": "ቀዳማይ ድኳንካ ብኸመይ ትፈጥር",
  "IP Address": "IP ኣድራሻ",
  "IP Addresses Blacklisted": "ዝተኣገዱ IP ኣድራሻታት",
  "IP address(es) blocked due to suspicious activity": "ብጥርጡር ንጥፈት ምኽንያት ዝተዓግቱ IP ኣድራሻ(ታት)",
  "IPs under restriction": "ኣብ ትሕቲ ገደብ ዘለዉ IP-ታት",
  "ISBN must be 10 or 13 characters.": "ISBN 10 ወይ 13 ፊደላት ክኸውን ኣለዎ።",
  "Image deleted": "ስእሊ ተደምሲሱ",
  "Image order updated": "ስርዓት ስእሊ ተመሓዪሹ",
  "Image uploaded": "ስእሊ ተጻዒኑ",
  "Implement request debouncing for search/filter operations": "ንፊልተርን ድልያን ስርሓት debouncing ተግብር",
  "Inactive": "ዘይንጡፍ",
  "Incorrect size": "ዘይቅኑዕ ዓቐን",
  "Integrations": "ውህደታት",
  "Internal notes": "ውሽጣዊ ማስታወሻታት",
  "Inventory": "ዕቃ",
  "Inventory Snapshot": "ስእሊ ዕቃ",
  "Inventory audit events": "ናይ ዕቃ ኦዲት ፍጻመታት",
  "Invite accepted! You can now log in.": "ዕድመ ተቐቢልና! ሕጂ ክትኣትዉ ትኽእሉ።",
  "Invite created.": "ዕድመ ተፈጢሩ።",
  "Invite link": "ናይ ዕድመ ሊንክ",
  "Invite link ready.": "ናይ ዕድመ ሊንክ ድሉው።",
  "Invite staff": "ስራሕተኛ ዕደም",
  "Invoice": "ኢንቮይስ",
  "Invoice management": "ምምሕዳር ኢንቮይስ",
  "Is my data secure with Selsa?": "ዳታይ ምስ ሰልሳ ውሑስ ድዩ?",
  "Items Ordered": "ዝተኣዘዙ ኣቑሑ",
  "Last 24h": "ዝሓለፈ 24 ሰዓት",
  "Last 30d": "ዝሓለፈ 30 መዓልቲ",
  "Last 7 days": "ዝሓለፈ 7 መዓልቲ",
  "Last 7d": "ዝሓለፈ 7 መዓልቲ",
  "Last login": "ናይ መወዳእታ ምእታው",
  "Late delivery": "ዝደንጎየ ምብጻሕ",
  "Linux": "Linux",
  "Loading order...": "ትእዛዝ ይጻዓን ኣሎ...",
  "Loading orders...": "ትእዛዛት ይጻዓኑ ኣለዉ...",
  "Loading timeline...": "ግዜ ሰሌዳ ይጻዓን ኣሎ...",
  "Local": "ናይ ቦታ",
  "Location": "ቦታ",
  "Logs": "ሎጋት",
  "Low": "ትሑት",
  "Low stock variants": "ትሑት ዕቃ ዘለዎም ቫርያንት",
  "Manage catalog availability.": "ትርከብነት ካታሎግ ኣመሓድር።",
  "Manage order fulfillment — submit to Printful, track shipments, handle exceptions.": "ምምላእ ትእዛዝ ኣመሓድር — ናብ Printful ስደድ, ምልኣኽ ተከታተል, ፍሉያት ኩነታት ኣመሓድር።",
  "Manage order lifecycle, shipping, and overrides.": "ዙርያ ህይወት ትእዛዝ, ምልኣኽ, ከምኡውን ምልዋጣት ኣመሓድር።",
  "Manage your devices and active sessions. Keep your account secure by removing\\n            unrecognized devices.": "መሳርሒታትኩምን ንጡፋት ክፍለ-ግዜታትን ኣመሓድሩ። ዘይፍለጡ መሳርሒታት ብምእላይ ኣካውንትኩም ውሑስ ግበሩ።",
  "Managing your profile": "ፕሮፋይልካ ኣብ ምምሕዳር",
  "Mark Received + Refund": "ከም ዝተቐበልና ምልከት + ገንዘብ ምለስ",
  "Mark shipped": "ከም ዝተላእከ ምልከት",
  "Medium": "ማእከላይ",
  "Min failed attempts": "ዝተሓተ ዝፈሸሉ ፈተነታት",
  "Never share your password with anyone. Always use a\\n            strong, unique password.": "ቃል-ምስጢርካ ንማንም ኣይትሃብ። ኩሉ ግዜ ብርቱዕን ፍሉይን ቃል-ምስጢር ተጠቐም።",
  "No alt text": "ኣልት ጽሑፍ የብሉን",
  "No audit events found.": "ናይ ኦዲት ፍጻመታት ኣይተረኸበን።",
  "No audit logs found.": "ናይ ኦዲት ሎጋት ኣይተረኸበን።",
  "No customers found.": "ዓማዊል ኣይተረኸቡን።",
  "No data": "ዳታ የለን",
  "No events to show yet.": "ገና ዝርአ ፍጻመ የለን።",
  "No notes yet.": "ገና ማስታወሻ የለን።",
  "No orders found.": "ትእዛዛት ኣይተረኸቡን።",
  "No orders in this stage.": "ኣብዚ ደረጃ ትእዛዝ የለን።",
  "No orders yet": "ገና ትእዛዝ የለን",
  "No products found.": "ፍርያታት ኣይተረኸቡን።",
  "No sessions to show": "ዝርአ ክፍለ-ግዜ የለን",
  "No slug": "Slug የብሉን",
  "No staff users found.": "ስራሕተኛታት ኣይተረኸቡን።",
  "No timeline events yet.": "ገና ናይ ግዜ ሰሌዳ ፍጻመ የለን።",
  "Not as described": "ከምቲ ዝተገልጸ ኣይኮነን",
  "Note added.": "ማስታወሻ ተወሲኹ።",
  "Note deleted.": "ማስታወሻ ተደምሲሱ።",
  "Note kind": "ዓይነት ማስታወሻ",
  "Note text is required.": "ጽሑፍ ማስታወሻ ይድለ።",
  "Note updated.": "ማስታወሻ ተመሓዪሹ።",
  "Notification preferences saved": "ምርጫታት ሓበሬታ ተዓቂቡ",
  "Nutrition facts (JSON)": "ሓቅታት ኣመጋግባ (JSON)",
  "Nutrition facts must be valid JSON.": "ሓቅታት ኣመጋግባ ቅኑዕ JSON ክኸውን ኣለዎ።",
  "Only local products can be deleted": "ናይ ቦታ ፍርያት ጥራይ ክድምሰስ ይኽእል",
  "Open": "ክፈት",
  "Open book": "መጽሓፍ ክፈት",
  "Open tickets": "ክፉታት ቲከታት",
  "Order": "ትእዛዝ",
  "Order Confirmed": "ትእዛዝ ተረጋጊጹ",
  "Order ID": "መለለዪ ትእዛዝ",
  "Order audit logs": "ናይ ትእዛዝ ኦዲት ሎጋት",
  "Order cannot be cancelled in its current status.": "ትእዛዝ ኣብ ዘለዎ ኩነታት ክስረዝ ኣይክእልን።",
  "Order marked as shipped.": "ትእዛዝ ከም ዝተላእከ ተመልኪቱ።",
  "Order not found.": "ትእዛዝ ኣይተረኸበን።",
  "Order status": "ኩነታት ትእዛዝ",
  "Order status filter": "ፊልተር ኩነታት ትእዛዝ",
  "Other": "ካልእ",
  "Overview": "ጽሟቕ",
  "Page size": "ዓቐን ገጽ",
  "Paid (awaiting)": "ዝተኸፍለ (ይጽበ)",
  "Password change failed": "ቃል-ምስጢር ምቕያር ፈሺሉ",
  "Password changed": "ቃል-ምስጢር ተቐዪሩ",
  "Password reset completed": "ቃል-ምስጢር ዳግም ምቕማጥ ተዛዚሙ",
  "Password reset requested": "ቃል-ምስጢር ዳግም ምቕማጥ ተሓቲቱ",
  "Payment Status:": "ኩነታት ክፍሊት:",
  "Payment pending": "ክፍሊት ይጽበ",
  "Payment:": "ክፍሊት:",
  "Performance": "ኣፈጻጽማ",
  "Placed": "ተቐሚጡ",
  "Please fill the required English fields before saving.": "ቅድሚ ምዕቃብ ዝድለዩ ናይ እንግሊዝ ዓውድታት ምልኡ።",
  "Please fill the required English fields before submitting.": "ቅድሚ ምስዳድ ዝድለዩ ናይ እንግሊዝ ዓውድታት ምልኡ።",
  "Please fill the required Tigrinya fields before saving.": "ቅድሚ ምዕቃብ ዝድለዩ ናይ ትግርኛ ዓውድታት ምልኡ።",
  "Please fill the required Tigrinya fields before submitting.": "ቅድሚ ምስዳድ ዝድለዩ ናይ ትግርኛ ዓውድታት ምልኡ።",
  "Previous": "ዝሓለፈ",
  "Price:": "ዋጋ:",
  "Primary image updated": "ቀንዲ ስእሊ ተመሓዪሹ",
  "Printful": "Printful",
  "Printful Sync Status": "ኩነታት ምትሕብባር Printful",
  "Printful products can't be deleted here. Unpublish it instead.": "ናይ Printful ፍርያት ኣብዚ ኣይድምሰስን። ኣብ ክንድኡ ዘይምሕታም ግበሩ።",
  "Process paid orders, add tracking, and mark shipments.": "ዝተኸፍሉ ትእዛዛት ኣሰርሕ, ትራኪንግ ወስኽ, ምልኣኽ ምልከት።",
  "Processing your order": "ትእዛዝኩም ይስራሕ ኣሎ",
  "Product deleted": "ፍርያት ተደምሲሱ",
  "Product published": "ፍርያት ተሕቲሙ",
  "Product unpublished": "ፍርያት ካብ ሕትመት ወጺኡ",
  "Product updated": "ፍርያት ተመሓዪሹ",
  "Profile updated": "ፕሮፋይል ተመሓዪሹ",
  "Promotional emails disabled": "ናይ ፕሮሞሽን ኢመይላት ተዓጽዩ",
  "Promotional emails enabled": "ናይ ፕሮሞሽን ኢመይላት ተኸፊቱ",
  "Provider": "ኣቕራቢ",
  "Purity / Karat (EN)": "ንጽህና / ካራት (EN)",
  "Purity / Karat (TI)": "ንጽህና / ካራት (TI)",
  "Reason": "ምኽንያት",
  "Reason (optional)": "ምኽንያት (ኣማራጺ)",
  "Reason (required for override)": "ምኽንያት (ንምልዋጥ ይድለ)",
  "Reason:": "ምኽንያት:",
  "Receipt": "ቅብሊት",
  "Reference": "ማዕቀፍ",
  "Refund": "ምምላስ ገንዘብ",
  "Refund Order": "ትእዛዝ ገንዘብ ምለስ",
  "Refund Request": "ሕቶ ምምላስ ገንዘብ",
  "Refund orders": "ትእዛዛት ገንዘብ ምለስ",
  "Refund policies": "ፖሊሲታት ምምላስ ገንዘብ",
  "Refund reason": "ምኽንያት ምምላስ ገንዘብ",
  "Refund request status:": "ኩነታት ሕቶ ምምላስ ገንዘብ:",
  "Reject": "ንጸግ",
  "Remove access": "ኣክሰስ ኣልይ",
  "Remove backoffice access for this user?": "ንዚ ተጠቃሚ ኣክሰስ ባክኦፊስ ክእለ?",
  "Removing...": "ይእለ ኣሎ...",
  "Report exported.": "ሪፖርት ወጺኡ።",
  "Report type": "ዓይነት ሪፖርት",
  "Reports": "ሪፖርታት",
  "Request Refund": "ምምላስ ገንዘብ ሕተት",
  "Request Return": "ምምላስ ሕተት",
  "Resend shipping": "ምልኣኽ ደጊምካ ስደድ",
  "Resend shipping email": "ናይ ምልኣኽ ኢመይል ደጊምካ ስደድ",
  "Resetting your password": "ቃል-ምስጢርካ ዳግም ኣብ ምቕማጥ",
  "Resolution breached": "ፍታሕ ተጊሒሱ",
  "Response times and priority levels vary based on your plan. Free plan users receive email support within 48-72 hours. \\n            Pro users within 24 hours. Business plan users get priority support and live chat. Enterprise customers have dedicated support managers with 1-hour response SLA.": "ግዜ መልስን ደረጃ ቀዳምነትን ብመሰረት ፕላንኩም ይፈላለ። ናጻ ፕላን ተጠቃሚታት ኣብ ውሽጢ 48-72 ሰዓታት ናይ ኢመይል ደገፍ ይረኽቡ። Pro ተጠቃሚታት ኣብ ውሽጢ 24 ሰዓታት። Business ፕላን ተጠቃሚታት ቀዳምነት ደገፍን ናይ ቀጥታ ቻትን ይረኽቡ።",
  "Return Instructions": "መምርሒታት ምምላስ",
  "Return Request": "ሕቶ ምምላስ",
  "Return reason": "ምኽንያት ምምላስ",
  "Return request status:": "ኩነታት ሕቶ ምምላስ:",
  "Return/Refund Requests": "ሕቶታት ምምላስ/ገንዘብ ምምላስ",
  "Review current alerts and suspicious login patterns.": "ሕጂ ዘለዉ ማንቂታትን ጥርጡር ኣገባብ ምእታውን ተረጋገጹ።",
  "Risk": "ሓደጋ",
  "Risk Monitoring": "ምክትታል ሓደጋ",
  "Risk level": "ደረጃ ሓደጋ",
  "Sales": "መሸጣ",
  "Sales Report": "ሪፖርት መሸጣ",
  "Sales and operational KPIs across the platform.": "ናይ መሸጣን ስርሓትን KPI-ታት ኣብ ፕላትፎርም።",
  "Save": "ዓቅብ",
  "Search by email or username": "ብኢመይል ወይ ስም ተጠቃሚ ድለ",
  "Search by order ID or email": "ብመለለዪ ትእዛዝ ወይ ኢመይል ድለ",
  "Search by order number": "ብቁጽሪ ትእዛዝ ድለ",
  "Search by slug or external id": "ብ slug ወይ ደጋዊ ID ድለ",
  "Search customers and review their orders.": "ዓማዊል ድለዩ ትእዛዛቶም ተረጋገጹ።",
  "Security monitoring and suspicious patterns": "ምክትታል ድሕነትን ጥርጡር ቅዲታትን",
  "Select a status for the bulk update.": "ንብጅምላ ምምሕያሽ ኩነታት ምረጹ።",
  "Select all orders": "ኩሎም ትእዛዛት ምረጽ",
  "Select at least one order.": "ብውሕዱ ሓደ ትእዛዝ ምረጹ።",
  "Select order": "ትእዛዝ ምረጽ",
  "Select status": "ኩነታት ምረጽ",
  "Selected": "ዝተመርጸ",
  "Send this link to the staff member:": "እዚ ሊንክ ንስራሕተኛ ስደድ:",
  "Sending...": "ይስደድ ኣሎ...",
  "Session refreshed": "ክፍለ-ግዜ ሓዲሹ",
  "Session revoked": "ክፍለ-ግዜ ተሰሪዙ",
  "Setting up payment methods": "ኣገባባት ክፍሊት ኣብ ምትዕርራይ",
  "Shipped": "ተላኢኹ",
  "Shipped & on its way": "ተላኢኹ ኣብ መንገዲ ኣሎ",
  "Shipping To": "ምልኣኽ ናብ",
  "Shipping email resent.": "ናይ ምልኣኽ ኢመይል ደጊሙ ተሰዲዱ።",
  "Shipping:": "ምልኣኽ:",
  "Showing page": "ዝርአ ገጽ",
  "Sign in to view your orders": "ትእዛዛትኩም ንምርኣይ ኣቲኹም ስርሑ",
  "Sign-in failed": "ምእታው ፈሺሉ",
  "Signed in": "ኣቲኻ",
  "Signed out": "ወጺኻ",
  "Signed out of other sessions": "ካብ ካልኦት ክፍለ-ግዜታት ወጺኻ",
  "Source": "ምንጪ",
  "Staff & Access": "ስራሕተኛታትን ኣክሰስን",
  "Staff email": "ኢመይል ስራሕተኛ",
  "Status filter": "ፊልተር ኩነታት",
  "Store ID (optional)": "መለለዪ ድኳን (ኣማራጺ)",
  "Stores": "ድኳናት",
  "Subtotal:": "ንኡስ ድምር:",
  "Support SLA": "ናይ ደገፍ SLA",
  "Suspend": "ዓግት",
  "System": "ስርዓት",
  "Tax Report": "ሪፖርት ቀረጽ",
  "Tax:": "ቀረጽ:",
  "Thank you for your purchase. Your order": "ስለ ዕድጊትኩም ነመስግን። ትእዛዝኩም",
  "Third-party integrations": "ናይ ሳልሳይ ወገን ውህደታት",
  "This month": "እዚ ወርሒ",
  "This package was returned to sender. Please contact support.": "እዚ ጥቕሊል ናብ ሰዳዲ ተመሊሱ። ደገፍ ተራኸቡ።",
  "This quarter": "እዚ ርብዒ ዓመት",
  "This shipment appears to be lost in transit. Our team is investigating.": "እዚ ምልኣኽ ኣብ መንገዲ ዝጠፍአ ይመስል። ጋንታና ይምርምር ኣሎ።",
  "This year": "እዚ ዓመት",
  "Timeline": "ግዜ ሰሌዳ",
  "Tips": "ምኽርታት",
  "Title (EN)": "ኣርእስቲ (EN)",
  "Title (TI)": "ኣርእስቲ (TI)",
  "Total Orders": "ጠቕላላ ትእዛዛት",
  "Total Revenue": "ጠቕላላ ኣታዊ",
  "Total orders": "ጠቕላላ ትእዛዛት",
  "Total revenue": "ጠቕላላ ኣታዊ",
  "Total spent": "ጠቕላላ ዝተወድአ",
  "Track Order": "ትእዛዝ ተከታተል",
  "Track important account security events": "ኣገደስቲ ፍጻመታት ድሕነት ኣካውንት ተከታተል",
  "Track order status, totals, and updates.": "ኩነታት ትእዛዝ, ድምርታት, ከምኡውን ምምሕያሽ ተከታተል።",
  "Tracking #": "ቁጽሪ ትራኪንግ",
  "Tracking number": "ቁጽሪ ትራኪንግ",
  "Translated by (EN)": "ዝተተርጎመ ብ (EN)",
  "Translated by (TI)": "ዝተተርጎመ ብ (TI)",
  "Two-factor authentication": "ክልተ-ደረጃ ምርግጋጽ",
  "Understanding the dashboard": "ዳሽቦርድ ምርዳእ",
  "Unknown": "ዘይፍሉጥ",
  "Unknown device": "ዘይፍሉጥ መሳርሒ",
  "Unpublish": "ካብ ሕትመት ኣውጽእ",
  "Unpublish and delete this product permanently? This cannot be undone.": "ንዚ ፍርያት ካብ ሕትመት ኣውጺኻ ንሓዋሩ ክትድምስሶ? እዚ ክምለስ ኣይክእልን።",
  "Update Status": "ኩነታት ኣመሓይሽ",
  "Update status": "ኩነታት ኣመሓይሽ",
  "Updated staff access.": "ናይ ስራሕተኛ ኣክሰስ ተመሓዪሹ።",
  "Updating your subscription": "ምዝገባኻ ኣብ ምምሕያሽ",
  "Updating...": "ይመሓየሽ ኣሎ...",
  "Use pagination for large data sets": "ንዓበይቲ ዳታ pagination ተጠቐም",
  "User": "ተጠቃሚ",
  "Variant ID": "መለለዪ ቫርያንት",
  "View All Orders": "ኩሎም ትእዛዛት ርአ",
  "View order": "ትእዛዝ ርአ",
  "We accept all major credit cards, PayPal, and bank transfers for enterprise customers.": "ኩሎም ዓበይቲ ክረዲት ካርድታት, PayPal, ከምኡውን ንናይ ኢንተርፕራይዝ ዓማዊል ናይ ባንክ ምስግጋር ንቕበል።",
  "We're preparing your items for production.": "ኣቑሑትኩም ንምስራሕ ነዳሉ ኣለና።",
  "Webhook configuration": "ኣተዓራርያ Webhook",
  "Welcome back! Here\\": "እንቋዕ ደሓን ተመለስኩም! እነሆ",
  "What Happens Next": "ቀጺሉ እንታይ ይኸውን",
  "What payment methods do you accept?": "እንታይ ኣገባባት ክፍሊት ትቕበሉ?",
  "When you place an order, it will appear here.": "ትእዛዝ ምስ ኣቐመጥኩም, ኣብዚ ክርአ እዩ።",
  "Windows": "Windows",
  "Wrong item": "ዘይቅኑዕ ኣቑሑ",
  "Yes, we use enterprise-grade encryption and regularly audit our systems. Check our Compliance page for detailed security information.": "እወ, ናይ ኢንተርፕራይዝ ደረጃ ምስጢራውነት ንጥቀምን ስርዓታትና ብቐጻሊ ነበርር። ንዝርዝር ሓበሬታ ድሕነት ገጽ Compliance ርአዩ።",
  "You can cancel your subscription anytime from the Billing section. Your access will continue until the end of your current billing period.": "ምዝገባኹም ኣብ ዝኾነ ግዜ ካብ ክፍሊ ክፍሊት ክትስርዝዎ ትኽእሉ። ኣክሰስኩም ክሳብ መወዳእታ ሕጂ ዘሎ ዙርያ ክፍሊት ክቕጽል እዩ።",
  "You need to be logged in to see your order history.": "ታሪኽ ትእዛዛትኩም ንምርኣይ ኣቲኹም ክትሰርሑ ኣለኩም።",
  "You'll receive a shipping confirmation with tracking info.": "ምርግጋጽ ምልኣኽ ምስ ሓበሬታ ትራኪንግ ክትቅበሉ ኢኹም።",
  "Your order is backordered. We'll notify you when it ships.": "ትእዛዝኩም ተመሊሱ ተኣዚዙ ኣሎ። ምስ ዝለኣኽ ክንሕብረኩም ኢና።",
  "e.g. 123": "ንኣብነት 123",
  "e.g. 456": "ንኣብነት 456",
  "e.g. ABC-123": "ንኣብነት ABC-123",
  "e.g. adjustment, reconciliation": "ንኣብነት ምትዕርራይ, ምትሕልላፍ",
  "e.g. cancel, refund": "ንኣብነት ስረዝ, ገንዘብ ምለስ",
  "e.g. staff@company.com": "ንኣብነት staff@company.com",
  "has been placed successfully.": "ብዓወት ተቐሚጡ።",
  "iOS device": "መሳርሒ iOS",
  "macOS": "macOS",
  "meta": "ሜታ",
  "page": "ገጽ",
  "Accept Invite": "ዕድመ ተቐበል",
  "Accept invite": "ዕድመ ተቐበል",
  "Account": "ኣካውንት",
  "Account Temporarily Locked": "ኣካውንት ንግዚኡ ተዓጽዩ",
  "Active Session": "ንጡፍ ክፍለ-ግዜ",
  "Active Sessions": "ንጡፋት ክፍለ-ግዜታት",
  "Active:": "ንጡፍ:",
  "Added": "ተወሲኹ",
  "Added:": "ተወሲኹ:",
  "Additional verification required": "ተወሳኺ ምርግጋጽ የድሊ",
  "Address Line 2": "ኣድራሻ መስመር 2",
  "All Products": "ኩሎም ፍርያት",
  "All Results": "ኩሎም ውጽኢታት",
  "Already accepted your invite?": "ድሮ ዕድመኻ ተቐቢልካ?",
  "Already have an account?": "ድሮ ኣካውንት ኣለካ?",
  "An unexpected error occurred": "ዘይተጸበናዮ ጸገም ተፈጢሩ",
  "Apt 4B, Suite 200, etc.": "ኣፓርትመንት 4B, ሱይት 200, ወዘተ.",
  "Apt, Suite, Unit (Optional)": "ኣፓርትመንት, ሱይት, ዩኒት (ኣማራጺ)",
  "Apt, suite, unit, etc. (optional)": "ኣፓርትመንት, ሱይት, ዩኒት, ወዘተ. (ኣማራጺ)",
  "Attempts remaining:": "ዝተረፈ ፈተነታት:",
  "Availability": "ትርከብነት",
  "Average Rating": "ማእከላይ ደረጃ",
  "Back to Home": "ናብ ገዛ ተመለስ",
  "Back to Login": "ናብ ምእታው ተመለስ",
  "Backpacks:": "ባርኖ:",
  "Based on actual carrier rates": "ብሓቂ ዋጋ ተሸከምቲ ዝተመስረተ",
  "Billing & Payment": "ክፍሊት",
  "Billing country options": "ኣማራጺታት ሃገር ክፍሊት",
  "Browse Categories": "ምድባት ርአ",
  "Browse Products": "ፍርያት ርአ",
  "Browse Store": "ድኳን ርአ",
  "Browse our collections and create unforgettable moments for your loved ones": "ትሕስቶታትና ፈትሹ እሞ ነቶም ተፍቅርዎም ዘይርሳዕ ህሞት ፍጠሩ",
  "Browse this category": "እዚ ምድብ ርአ",
  "Bulk Discounts:": "ናይ ብጅምላ ቅናስ:",
  "Calculation": "ኣገባብ ምሕሳብ",
  "Call our support team for immediate assistance.": "ንቕልጡፍ ሓገዝ ናብ ጋንታ ደገፍና ደውሉ።",
  "Card Details": "ሓበሬታ ካርድ",
  "Cart": "ጋልማ",
  "Categories Only": "ምድባት ጥራይ",
  "Category Insights": "ትንተና ምድብ",
  "Ceramic drinkware (standard rate)": "ናይ ሰራሚክ ናውቲ (ስሩዕ ዋጋ)",
  "Change Password": "ቃል-ምስጢር ቀይር",
  "Change your account password": "ቃል-ምስጢር ኣካውንትኻ ቀይር",
  "Changing...": "ይቕየር ኣሎ...",
  "Checkout steps": "ስጉምትታት ዕድጊት",
  "Choose your preferred way to contact us - email, chat, phone, or WhatsApp.": "ዝመረጽኩሞ ኣገባብ ርክብ ምረጹ — ኢመይል, ቻት, ስልኪ, ወይ ዋትስኣፕ።",
  "Clear All": "ኩሉ ኣጽሪ",
  "Color:": "ሕብሪ:",
  "Compare (": "ኣነጻጽር (",
  "Compare Selected": "ዝተመርጹ ኣነጻጽር",
  "Confirm New Password": "ሓድሽ ቃል-ምስጢር ኣረጋግጽ",
  "Confirm password": "ቃል-ምስጢር ኣረጋግጽ",
  "Connect with our team immediately for quick answers.": "ንቕልጡፍ መልሲ ምስ ጋንታና ተራኸቡ።",
  "Connection lost after payment. Your payment was received — your order will appear on your Orders page shortly. If not, please contact support.": "ድሕሪ ክፍሊት ርክብ ተቋሪጹ። ክፍሊትኩም ተቐቢልና — ትእዛዝኩም ኣብ ገጽ ትእዛዛትኩም ቀርቢ ክርአ እዩ።",
  "Connection lost. Please check your internet and try again.": "ርክብ ተቋሪጹ። ኢንተርነትኩም ተረጋጊጹ ደጊምኩም ፈትኑ።",
  "Connection lost. Your payment is safe.": "ርክብ ተቋሪጹ። ክፍሊትኩም ውሑስ እዩ።",
  "Contact": "ርክብ",
  "Contact Support": "ደገፍ ተራኸብ",
  "Contact Support Now": "ሕጂ ደገፍ ተራኸብ",
  "Contact our design team today for a free consultation": "ንነጻ ምኽሪ ሎሚ ንጋንታ ዲዛይንና ተራኸቡ",
  "Continue": "ቀጽል",
  "Continue with :": "ቀጽል ብ:",
  "Cost": "ዋጋ",
  "Coupon Applied:": "ኩፖን ተተግቢሩ:",
  "Create New Password": "ሓድሽ ቃል-ምስጢር ፍጠር",
  "Current Password": "ሕጂ ዘሎ ቃል-ምስጢር",
  "Customer Reviews": "ገምጋማት ዓማዊል",
  "Dashboard": "ዳሽቦርድ",
  "Delivery.": "ምብጻሕ.",
  "Discount:": "ቅናስ:",
  "Don\\": "ኣይት",
  "Duration:": "ንውሓት ግዜ:",
  "Each Additional Item:": "ነፍሲ ወከፍ ተወሳኺ ኣቑሑ:",
  "Each Additional:": "ነፍሲ ወከፍ ተወሳኺ:",
  "Each product has a category that determines its shipping rate:": "ነፍሲ ወከፍ ፍርያት ዋጋ ምልኣኹ ዝውስን ምድብ ኣለዎ:",
  "Email Sent!": "ኢመይል ተሰዲዱ!",
  "Email Support": "ብኢመይል ደገፍ",
  "Emergency Support": "ህጹጽ ደገፍ",
  "Enter a search query to find products and categories": "ፍርያትን ምድባትን ንምርካብ ድለ",
  "Enter tracking number": "ቁጽሪ ትራኪንግ ኣእቱ",
  "Enter your tracking number to see real-time delivery updates": "ናይ ብቐጥታ ሓበሬታ ምብጻሕ ንምርኣይ ቁጽሪ ትራኪንግኻ ኣእቱ",
  "Estimated Delivery:": "ግምት ምብጻሕ:",
  "European Union": "ሕብረት ኤውሮጳ",
  "Example: 2 Hoodies = 8.99 + (2.99 × 1) =": "ኣብነት: 2 ሁዲ = 8.99 + (2.99 × 1) =",
  "Example: 3 T-shirts = 5.99 + (1.99 × 2) =": "ኣብነት: 3 ቲ-ሸርት = 5.99 + (1.99 × 2) =",
  "Example: 4 Items = 14.99 + (4.99 × 3) =": "ኣብነት: 4 ኣቑሑ = 14.99 + (4.99 × 3) =",
  "Expert Team": "ክኢላ ጋንታ",
  "Explore Gifts": "ህያባት ርአ",
  "Explore our complete collection of products": "ምሉእ ትሕስቶ ፍርያትና ርአ",
  "Express Shipping": "ቅልጡፍ ምልኣኽ",
  "Failed to accept invite.": "ዕድመ ምቕባል ኣይተሰለጠን።",
  "Failed to change password": "ቃል-ምስጢር ምቕያር ኣይተሰለጠን",
  "Failed to load image": "ስእሊ ምጽዓን ኣይተሰለጠን",
  "Failed to submit review.": "ገምጋም ምጽሓፍ ኣይተሰለጠን።",
  "Fair Pricing:": "ርትዓዊ ዋጋ:",
  "Fast Response": "ቕልጡፍ መልሲ",
  "Fill out the form below and we\\": "ኣብ ታሕቲ ዘሎ ቅጥዒ ምልኡ እሞ ንሕና",
  "Filter:": "ፊልተር:",
  "Filters & Sort": "ፊልተራትን ሰርዕን",
  "Find comprehensive answers to all your questions about our services, products, and policies.": "ብዛዕባ ኣገልግሎትና, ፍርያትናን ፖሊሲታትናን ንኩሉ ሕቶታትኩም ምሉእ መልሲ ርኸቡ።",
  "First Item Rate:": "ዋጋ ቀዳማይ ኣቑሑ:",
  "First Item:": "ቀዳማይ ኣቑሑ:",
  "First item at full rate, additional items at reduced rate": "ቀዳማይ ኣቑሑ ብምሉእ ዋጋ, ተወሳኺ ኣቑሑ ብዝጎደለ ዋጋ",
  "For critical issues affecting your business operations.": "ኣብ ስራሕኩም ጽልዋ ንዘለዎም ህጹጻት ጉዳያት።",
  "Found": "ተረኺቡ",
  "Fraud Protection": "ምክልኻል ምትላል",
  "Frequently Asked Questions": "ብተደጋጋሚ ዝሕተቱ ሕቶታት",
  "Get Started": "ጀምር",
  "Get help, manage security, and contact us": "ሓገዝ ርኸብ, ድሕነት ኣመሓድር, ተራኸበና",
  "Gift & Surprise Events": "ህያብን ዘይተጸበናዮን ኣጋጣሚታት",
  "Gift Wrapping & Packaging Options": "ኣማራጺታት ምጥቕላል ህያብ",
  "Go back to": "ናብ ተመለስ",
  "Go to Login": "ናብ ምእታው",
  "Go to favourites": "ናብ ፍቱዋት",
  "Go to next step": "ናብ ዝቕጽል ስጉምቲ",
  "Go to previous step": "ናብ ዝሓለፈ ስጉምቲ",
  "Go to your account": "ናብ ኣካውንትኻ",
  "Got it! Close": "ርድኢት! ዕጾ",
  "Have questions or ready to transform your brand? We\\": "ሕቶ ኣለኩም ወይ ብራንድኩም ንምቕያር ድሉዋት?",
  "Heart your favorite products to save them here for later.": "ፍቱዋት ፍርያትኩም ንደሓር ኣብዚ ዓቅቡ።",
  "Heavier apparel (standard rate)": "ከበድቲ ክዳውንቲ (ስሩዕ ዋጋ)",
  "Highest Rated": "ዝለዓለ ደረጃ",
  "Home": "ገዛ",
  "Hoodie (1st item):": "ሁዲ (1ይ ኣቑሑ):",
  "Hoodies:": "ሁዲታት:",
  "How Shipping is Calculated": "ምልኣኽ ብኸመይ ይሕሰብ",
  "IP:": "IP:",
  "If the wallet button is unavailable, use the payment form below.": "ናይ ዋለት መልጎም ዘይርከብ እንተኾይኑ, ኣብ ታሕቲ ዘሎ ቅጥዒ ክፍሊት ተጠቐሙ።",
  "In Stock Only": "ኣብ ዕቃ ዘሎ ጥራይ",
  "Initiate Return": "ምምላስ ጀምር",
  "Insights": "ትንተናታት",
  "Inspired by Abubeker Haji Hassen --  ስለምንታይ ... እቲ ዘለና\\": "ብኣቡበከር ሓጂ ሓሰን ዝተተባብዐ -- ስለምንታይ ... እቲ ዘለና",
  "Instant messaging": "ቅልጡፍ መልእኽቲ",
  "Invalid invite": "ዘይቅኑዕ ዕድመ",
  "Invite accepted. You can now log in.": "ዕድመ ተቐቢልና። ሕጂ ክትኣትዉ ትኽእሉ።",
  "Invite link or token": "ናይ ዕድመ ሊንክ ወይ ቶከን",
  "Invite sent!": "ዕድመ ተሰዲዱ!",
  "Invite token:": "ቶከን ዕድመ:",
  "Let\\": "ንፍቀድ",
  "Load more reviews": "ተወሳኺ ገምጋማት ጽዓን",
  "Log in": "ኣቲኻ ስራሕ",
  "Message us directly on WhatsApp for quick assistance.": "ንቕልጡፍ ሓገዝ ብዋትስኣፕ ቀጥታ ጽሓፉልና።",
  "Mon - Fri, 10AM - 8PM": "ሰሉስ - ዓርቢ, 10AM - 8PM",
  "Mon - Fri, 9AM - 6PM": "ሰሉስ - ዓርቢ, 9AM - 6PM",
  "Most inquiries are resolved within hours, not days.": "መብዛሕትኡ ሕቶታት ኣብ ሰዓታት እዩ ዝፍታሕ, ኣብ መዓልታት ኣይኮነን።",
  "Multiple Channels": "ብዙሕ ኣገባባት",
  "No internet connection. Please check your connection and try again.": "ኢንተርነት ኣይርከብን። ርክብኩም ተረጋጊጹ ደጊምኩም ፈትኑ።",
  "No products found in this category": "ኣብዚ ምድብ ፍርያት ኣይተረኸበን",
  "No reviews yet. Be the first to review this product!": "ገምጋም የለን ገና። ቀዳማይ ገምጋሚ ኩኑ!",
  "Not enough stock available.": "ብቑዕ ዕቃ ኣይርከብን።",
  "Only {{count}} left": "{{count}} ጥራይ ተሪፉ",
  "Our support specialists are trained to handle any issue quickly and professionally.": "ናይ ደገፍ ክኢላታትና ንኹሉ ጸገም ብቕልጣፈን ብሞያዊነትን ንምፍታሕ ሰልጢኖም እዮም።",
  "Overnight Shipping": "ናይ ለይቲ ምልኣኽ",
  "Password changed successfully": "ቃል-ምስጢር ብዓወት ተቐዪሩ",
  "Password is required.": "ቃል-ምስጢር ይድለ።",
  "Password must be at least 8 characters": "ቃል-ምስጢር ብውሕዱ 8 ፊደላት ክኸውን ኣለዎ",
  "Passwords do not match": "ቃል-ምስጢራት ኣይሰማምዑን",
  "Passwords do not match.": "ቃል-ምስጢራት ኣይሰማምዑን።",
  "Paste a valid invite link or token.": "ቅኑዕ ናይ ዕድመ ሊንክ ወይ ቶከን ለጥፍ።",
  "Paste the invite link or token you received to continue.": "ንምቕጻል ዝተቐበልኩሞ ናይ ዕድመ ሊንክ ወይ ቶከን ለጥፉ።",
  "Pay": "ክፈል",
  "Pay and continue": "ክፈልን ቀጽልን",
  "Pay with Apple Pay": "ብ Apple Pay ክፈል",
  "Pay with Google Pay": "ብ Google Pay ክፈል",
  "Payment Details": "ዝርዝር ክፍሊት",
  "Payment successful! Placing your order...": "ክፍሊት ተሰሊጡ! ትእዛዝኩም ይቐርብ ኣሎ...",
  "Placing Your Order": "ትእዛዝኩም ይቐርብ ኣሎ",
  "Please select a rating.": "ደረጃ ምረጹ።",
  "Please wait while we place your order...": "ትእዛዝኩም ክነቐርብ ከለና ተጸበዩ...",
  "Pre-order": "ቅድመ-ትእዛዝ",
  "Price updated to {{price}}": "ዋጋ ናብ {{price}} ተመሓዪሹ",
  "Redeem Staff Invite": "ናይ ስራሕተኛ ዕድመ ተጠቐም",
  "Redirecting to your order confirmation...": "ናብ ምርግጋጽ ትእዛዝኩም ይውሰድ ኣሎ...",
  "Refresh payment": "ክፍሊት ሓድሽ",
  "Registration failed. Please check your details and try again.": "ምምዝጋብ ኣይተሰለጠን። ዝርዝርኩም ተረጋጊጹ ደጊምኩም ፈትኑ።",
  "Registration successful! You can now log in.": "ምምዝጋብ ተሰሊጡ! ሕጂ ክትኣትዉ ትኽእሉ።",
  "Retry Placing Order": "ትእዛዝ ደጊምካ ፈትን",
  "Review submitted! It will appear after moderation.": "ገምጋም ተሰዲዱ! ድሕሪ ምፍታሽ ክርአ እዩ።",
  "Send us an email and we'll respond within 24 hours with solutions.": "ኢመይል ስደዱልና ኣብ ውሽጢ 24 ሰዓታት ፍታሕ ክንምልስ ኢና።",
  "Services": "ኣገልግሎታት",
  "Set your password to activate your staff account.": "ናይ ስራሕተኛ ኣካውንትኻ ንምንቃል ቃል-ምስጢር ኣቐምጥ።",
  "Share details of your experience with this product": "ብዛዕባ ተመኩሮኻ ምስ እዚ ፍርያት ኣካፍል",
  "Shipping country options": "ኣማራጺታት ሃገር ምልኣኽ",
  "Sign in to leave a review.": "ገምጋም ንምጽሓፍ ኣቲኻ ስራሕ።",
  "Some items are no longer available.": "ገለ ኣቑሑ ድሮ ኣይርከቡን እዮም።",
  "Standard Shipping": "ስሩዕ ምልኣኽ",
  "Submit Review": "ገምጋም ስደድ",
  "Submitting...": "ይስደድ ኣሎ...",
  "Summarize your experience": "ተመኩሮኻ ጠቅልል",
  "The first item in each category ships at the full rate. Each additional item\\n              ships at a reduced rate, making bulk orders more affordable.": "ኣብ ነፍሲ ወከፍ ምድብ ቀዳማይ ኣቑሑ ብምሉእ ዋጋ ይለኣኽ። ነፍሲ ወከፍ ተወሳኺ ኣቑሑ ብዝጎደለ ዋጋ ይለኣኽ, ብጅምላ ምእዛዝ ክትጥቀሙ ይሕግዝ።",
  "The link will expire in 1 hour. Check your spam folder if you don\\": "ሊንክ ኣብ ውሽጢ 1 ሰዓት ክውዳእ እዩ። ኣብ ስፓም ፎልደር ፈትሹ",
  "The price for this item has been updated. Please review before proceeding.": "ዋጋ ናይ እዚ ኣቑሑ ተመሓዪሹ። ቅድሚ ምቕጻል ተረጋገጹ።",
  "This is taking longer than usual. Your payment is safe.": "ካብ ንቡር ንላዕሊ ይደንጊ ኣሎ። ክፍሊትኩም ውሑስ እዩ።",
  "This item is currently out of stock.": "እዚ ኣቑሑ ሕጂ ኣብ ዕቃ ኣይርከብን።",
  "Title": "ኣርእስቲ",
  "Token detected": "ቶከን ተረኺቡ",
  "Urgent issues only": "ህጹጻት ጉዳያት ጥራይ",
  "Username": "ስም ተጠቃሚ",
  "Username (optional)": "ስም ተጠቃሚ (ኣማራጺ)",
  "Validating order, attempt {{attempt}}...": "ትእዛዝ ይረጋገጽ ኣሎ, ፈተነ {{attempt}}...",
  "Verified Purchase": "ዝተረጋገጸ ዕድጊት",
  "View My Orders": "ትእዛዛተይ ርአ",
  "We couldn\\": "ኣይከኣልናን",
  "We updated your totals based on the latest pricing. Please review before paying.": "ድምር ዋጋኹም ብመሰረት ሓድሽ ዋጋ ተመሓዪሹ። ቅድሚ ምኽፋል ተረጋገጹ።",
  "We\\": "ንሕና",
  "You can wait, or check your orders page — your order may already be there.": "ክትጽበዩ ትኽእሉ, ወይ ገጽ ትእዛዛትኩም ርአዩ — ትእዛዝኩም ድሮ ኣብኡ ክኸውን ይኽእል።",
  "You may be redirected to complete payment with your selected provider.": "ክፍሊት ንምዝዛም ናብ ዝመረጽኩሞ ኣቕራቢ ክትውሰዱ ትኽእሉ።",
  "You\\": "ንስኻ",
  "Your Rating": "ደረጃኻ",
  "Your payment information is securely processed by Stripe.": "ሓበሬታ ክፍሊትኩም ብ Stripe ብውሑስ ኣገባብ ይስራሕ።",
  "Your payment session expired. Please refresh and try again.": "ናይ ክፍሊት ክፍለ-ግዜ ወዲኡ። ሓድሽ ገይርኩም ደጊምኩም ፈትኑ።",
  "Your payment was processed successfully. If your order doesn\\": "ክፍሊትኩም ብዓወት ተሰሪሑ። ትእዛዝኩም እንተዘይተራእዩ",
  "Your payment was received but we had trouble creating your order. Please check your Orders page in a few minutes, or contact support if the order does not appear.": "ክፍሊትኩም ተቐቢልና ግን ትእዛዝኩም ኣብ ምፍጣር ጸገም ነይሩ። ገጽ ትእዛዛትኩም ኣብ ውሽጢ ቅሩብ ደቓይቕ ፈትሹ, ወይ ትእዛዙ እንተዘይተራእዩ ደገፍ ተራኸቡ።",
  "optional": "ኣማራጺ"
};

// Read missing keys
const missingKeys = require('/tmp/remaining_keys.json');

let added = 0;
for (const key of missingKeys) {
  // Add to EN (key = value)
  if (!(key in en)) {
    en[key] = key;
    added++;
  }
  // Add to TI (use proper translation or key as fallback)
  if (!(key in ti)) {
    ti[key] = tiTranslations[key] || key;
  }
}

fs.writeFileSync(enPath, JSON.stringify(en, null, 2) + '\n');
fs.writeFileSync(tiPath, JSON.stringify(ti, null, 2) + '\n');

const enCount = Object.keys(en).length;
const tiCount = Object.keys(ti).length;
console.log(`Added ${added} keys`);
console.log(`EN: ${enCount} keys | TI: ${tiCount} keys | Match: ${enCount === tiCount}`);
